### ISSUE TITLE
AFDX ?

### ISSUE THREAD

**Issue by Germwalker** [OpenCyphal/specification#133]
Hello, 

I was wondering if you thought about (in a far futur) implement Cyphal over AFDX ? 
Maybe it is not compatible as both are protocols over the IP layer ?

**Comment by pavel-kirienko** [comment]
It's not impossible. While AFDX is rather rigid compared to Cyphal due to the predefined VL configuration, sensible mapping of a limited subset of Cyphal should be possible. Whether it is meaningful is a different question. Can you please provide any background or justification for your request and perhaps a few words about the intended application?

See relevant notes here: https://forum.opencyphal.org/t/generalized-mapping-of-cyphal-to-transports/1761

Please reply in a new thread on the forum; I am closing this issue since GitHub is not the best place for discussions of this kind.
